name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Use Node.js latest
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Install node dependencies
        run: |
          npm i -g pnpm
          pnpm i
      - name: Run lint
        run: |
          pnpm run lint
      - name: Install emsdk
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
      - name: Build wasm
        run: |
          . emsdk/emsdk_env.sh
          pnpm run lib
          pnpm run wasm
      - name: Build
        run: |
          pnpm run build
      - name: Upload artifact
        if: ${{ github.ref == 'refs/heads/master' && matrix.os == 'ubuntu-latest' }}
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  test:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js latest
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Install node dependencies
        run: |
          npm i -g pnpm
          pnpm i
          npx playwright install
          npx playwright install-deps
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Test
        run: |
          pnpm run test
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mv dist my-font-converter-dist
          zip -r my-font-converter-dist.zip my-font-converter-dist
          gh release upload latest my-font-converter-dist.zip --clobber
